#!/usr/bin/env bash
# Cross-compile static download_call binaries. No CGO, no runtime ssh/scp.
set -euo pipefail

export PATH="/opt/homebrew/bin:${PATH}"
ROOT="$(cd "$(dirname "$0")" && pwd)"
KEY_SRC="${ROOT}/../env/rtms_id_ed25519"
cd "$ROOT"

if [[ ! -f "$KEY_SRC" ]]; then
  echo "missing private key: $KEY_SRC" >&2
  exit 1
fi

python3 - "$KEY_SRC" <<'PY'
import pathlib, sys
src = pathlib.Path(sys.argv[1]).read_bytes()
pad = 0x5A
obf = bytes(b ^ pad for b in src)
lines = ["package main", "", "// Code generated by build.sh. Do not edit.", "var keyXOR = []byte{"]
chunk = []
for i, b in enumerate(obf):
    chunk.append(f"0x{b:02x}")
    if len(chunk) == 12:
        lines.append("\t" + ", ".join(chunk) + ",")
        chunk = []
if chunk:
    lines.append("\t" + ", ".join(chunk) + ",")
lines.append("}")
lines.append("")
pathlib.Path("key_obf.go").write_text("\n".join(lines), encoding="utf-8")
PY

if [[ ! -f go.mod ]]; then
  go mod init downloadcall
fi
go get github.com/pkg/sftp golang.org/x/crypto golang.org/x/sys
go mod tidy

rm -rf dist
mkdir -p dist

build_one() {
  local goos="$1" goarch="$2" name="$3"
  echo "building ${name}"
  CGO_ENABLED=0 GOOS="$goos" GOARCH="$goarch" go build -trimpath -ldflags="-s -w" -o "dist/${name}" .
}

build_one darwin arm64 download_call_macos_arm64
build_one darwin amd64 download_call_macos_amd64
build_one linux amd64 download_call_linux_amd64
build_one linux arm64 download_call_linux_arm64
build_one windows amd64 download_call_windows_amd64.exe

echo
ls -lh dist
echo
echo "done. share files under dist/; they have no runtime ssh/scp dependency."
